destination:    ./_site
lsi:            false
pygments:       true
exclude:        ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss"]
permalink:      /:title
markdown:       kramdown
markdown_ext:   markdown,mkd,mkdn,md
name:           Joel Glovier's Blog
description:    "The personal site of Joel Andrew Glovier, designer and front-end technologist. Where I write about code, design, faith, food, and life. Views expressed are my own. Use code at your own risk."
url:            http://joelglovier.com
gems:
  - jekyll-redirect-from
  - powered-by-pages