destination:    ./_site
safe:           true
lsi:            false
pygments:       true
exclude:        ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss"]
permalink: /writing/:categories/:year/:title
markdown:       kramdown
markdown_ext:   markdown,mkd,mkdn,md
